function deepFreeze(obj) {
  Object.values(obj).forEach((value) => {
    if (value && typeof value === "object") deepFreeze(value);
  });
  return Object.freeze(obj);
}

export const LETTERS_COPY = deepFreeze({
  tabs: {
    issue: "Issue a letter",
    issued: "Issued letters",
    offers: "Offer candidates",
    ariaLabel: "Letters sections",
  },
  home: {
    title: "Issue a letter",
    description: "Choose the letter you want to issue. Details are filled in from the person's record.",
    searchLabel: "Search letters",
    searchPlaceholder: "Search letters, e.g. experience",
    clearSearch: "Clear search",
    recent: "Recently issued",
    recentEmpty: "No letters issued yet. Letters you issue will appear here.",
    recentError: "Could not load recently issued letters.",
    viewAll: "View all issued letters",
    manage: "Manage templates",
    empty: "No letters match “{query}”.",
  },
  manage: {
    title: "Manage templates",
    description: "Change the wording of your letters or create your own. Issued letters are not affected.",
    back: "Back to letters",
    create: "Create template",
    searchLabel: "Search templates",
    show: "Show",
    statusActive: "Active",
    statusArchived: "Archived",
    columns: { name: "Name", group: "Group", whoFor: "Who it's for", updated: "Last updated" },
    caption: "Letter templates",
    badgeDefault: "Default",
    badgeCustomised: "Customised",
    badgeArchived: "Archived",
    edit: "Edit",
    view: "View",
    duplicate: "Duplicate",
    archive: "Archive",
    restore: "Restore",
    loadError: "Templates could not be loaded",
    loadErrorHint: "Check your connection and try again.",
    retry: "Retry",
    noMatch: "No templates match your search",
    noMatchHint: "Try a different word or clear the search.",
    noArchived: "No archived templates",
    noTemplates: "No templates yet",
    duplicateTitle: "Duplicate template",
    duplicateName: "New template name",
    templateNameLabel: "Template name",
    duplicateSuffix: "{name} (copy)",
    duplicated: "Template duplicated.",
    archiveTitle: "Archive “{name}”?",
    archiveMessage:
      "It is no longer offered when issuing letters. Letters already issued are not affected, and you can restore it any time.",
    archived: "Template archived.",
    restored: "Template restored.",
    actionError: "That action failed. Please try again.",
  },
  recipientTypes: {
    employee: "Employee",
    candidate: "Offer candidate",
  },
  issued: {
    title: "Issued letters",
    description: "Every letter you have issued, with its PDF and letter number.",
    issueButton: "Issue a letter",
    emptyHint: "Letters you issue appear here with their PDFs.",
    searchPlaceholder: "Search by name or letter number",
    searchLabel: "Search issued letters",
    templateFilter: "Template",
    allTemplates: "All templates",
    personFilter: "Who it's for",
    everyone: "Everyone",
    statusFilter: "Status",
    anyStatus: "Any status",
    caption: "Issued letters",
    columns: { letter: "Letter", person: "Person", issued: "Issued", status: "Status" },
    issuedBy: "by {name}",
    edited: "Edited",
    emailed: "Emailed",
    showingFor: "Showing letters for",
    selectedPerson: "the selected person",
    showAll: "Show all",
    loadError: "Issued letters could not be loaded",
    loadErrorHint: "Check your connection and try again.",
    retry: "Retry",
    noMatch: "No letters match your filters",
    noMatchHint: "Try a different search or filter.",
    empty: "No letters issued yet",
    pageSummary: "letters",
    view: "View",
    download: "Download",
    emailAction: "Email to recipient",
    emailActionDisabled: "Email (no email on file)",
    voidAction: "Void",
    downloadError: "Could not download the letter.",
    emailTitle: "Email this letter?",
    emailMessage: "The PDF is sent to {email}.",
    emailConfirm: "Send email",
    emailedToast: "Emailed to {email}.",
    emailError: "Could not send the email.",
    voidTitle: "Void {number}?",
    voidMessage:
      "The letter stays on record but is marked void, and its document is removed from the recipient's documents. This cannot be undone.",
    voidConfirm: "Void letter",
    voidReason: "Reason",
    voided: "Letter voided.",
    voidError: "Could not void the letter.",
    viewerFallbackTitle: "Letter",
    viewerSubtitle: "{name} · {number}",
    viewerVoided: "Voided",
    viewerVoidedOn: "Voided on {date}",
    opening: "Opening letter…",
    openError: "Could not open this letter.",
    pdfTitle: "Issued letter PDF",
  },
  issue: {
    title: "Issue a letter",
    chooseTitle: "Which letter do you want to issue?",
    chooseSearch: "Search letters",
    noTemplates: "No letters are available to issue here.",
    loadingTemplates: "Loading letters…",
    loadTemplatesError: "Could not load letters. Try again in a moment.",
    templateUnavailable: "That letter is no longer available. Choose another letter below.",
    templateKeyUnavailable: "No {name} template is available — choose a letter.",
    templateKeyUnavailableGeneric: "That letter template is not available — choose a letter.",
    forPerson: "For {name}",
    changeLetter: "Choose a different letter",
    who: "Who is this for?",
    searchEmployees: "Name, employee code or email",
    searchCandidates: "Name or email",
    choosePerson: "Choose a person",
    loadingPeople: "Loading people…",
    loadPeopleError: "Could not load people. Try again in a moment.",
    noPeople: "No one found.",
    noPeopleMatch: "No one matches “{query}”.",
    noOfferCandidates: "No candidates waiting for an offer. Add a candidate in Offer candidates first.",
    noCandidates: "No candidates yet. Add a candidate in Offer candidates first.",
    goToOffers: "Go to Offer candidates",
    chooseRecipient: "Choose who this letter is for",
    change: "Change",
    noEmailOnFile: "No email on file",
    personStatus: { inactive: "Inactive", exited: "Exited" },
    details: "A few details for this letter",
    selectPlaceholder: "Select…",
    noDetails: "Nothing else is needed — everything is filled in from the record.",
    optionalHint: "(optional — leave blank to skip this line)",
    lockedByEdits: "You edited the wording, so these answers are locked. Use “Undo my changes” to change them.",
    noEmail: "This person has no email on file — you can still download the letter.",
    blankDetails:
      "These details are blank for {name}: {list}. They'll print as gaps — update the {record} record or edit the wording.",
    recordEmployee: "employee",
    recordCandidate: "candidate",
    companyIncomplete: "Add your company name and address in Settings → Organization profile before issuing letters.",
    openSettings: "Open Organization profile",
    checkCompanyAgain: "Check again",
    sendEmail: "Email the PDF to {email}",
    sendEmailDisabled: "Email the PDF (no email on file)",
    previewTitle: "Letter preview",
    previewEmpty: "Choose who this letter is for to see the letter.",
    previewError: "Could not show the letter. Try again in a moment.",
    retryPreview: "Try again",
    stillNeeded: "Still needed: {list}",
    editWording: "Edit wording for this letter",
    answerFirst: "Answer the questions to edit the wording.",
    editNote: "Changes apply to this letter only — the template stays the same.",
    apply: "Apply changes",
    cancel: "Cancel",
    edited: "Edited for this letter",
    emptyLetter: "The letter cannot be empty.",
    undo: "Undo my changes",
    downloadDraft: "Download draft",
    draftNeedsAnswers: "Answer the required questions to download a draft.",
    draftError: "Could not download the draft. Try again in a moment.",
    issue: "Issue letter",
    issueError: "Could not issue the letter. Try again in a moment.",
    issueBlockedCompany: "Add your company details to issue letters.",
    success: "Letter issued",
    successSummary: "{letter} for {name} · Letter no. {number}",
    emailed: "Emailed to {email}",
    emailFailed: "The letter was issued but the email could not be sent. You can resend it from Issued letters.",
    savedNote: "The PDF is saved in the person's documents and in Issued letters.",
    issuedToast: "{letter} issued.",
    issuedEmailedToast: "{letter} issued and emailed.",
    downloadPdf: "Download PDF",
    downloadError: "Could not download the letter. Try again in a moment.",
    issueAnother: "Issue another",
    viewIssued: "View issued letters",
    done: "Done",
  },
  editor: {
    questions: "Questions to ask when issuing",
    questionsTab: "Questions",
    questionsGroup: "This letter's questions",
    letterhead: "Letterhead",
    about: "About",
    whoFor: "Who is this letter for?",
    whoForFixed: "Fixed for built-in templates",
    whoForHint: "Changes which details you can insert.",
    group: "Group",
    back: "Back to templates",
    newTemplate: "New template",
    nameLabel: "Template name",
    unsaved: "Unsaved changes",
    previewSample: "Preview with sample data",
    previewTitle: "Template preview with sample data",
    previewEmpty: "Add some letter content to see a preview.",
    previewError: "Preview failed. Check the letter content.",
    previewMissing: "Sample data has no value for: {list}.",
    tryIssuing: "Try issuing",
    tryIssuingNew: "Save the template first, then try issuing it.",
    tryIssuingConfirmTitle: "Save your changes first?",
    tryIssuingConfirmMessage: "Try issuing uses the saved template. Save your changes now and continue?",
    saveAndTryIssuing: "Save and try issuing",
    save: "Save",
    create: "Create template",
    saveConfirm: "Save",
    saveNoteHint: "Shown in the template's history.",
    saveNoteLabel: "Change note",
    saved: "Saved as version {version}.",
    created: "Template created.",
    saveError: "Could not save the template.",
    fixErrors: "Please fix the highlighted fields before saving.",
    reload: "Reload",
    reloadConfirmTitle: "Reload and lose your changes?",
    reloadConfirmMessage: "Your unsaved edits are replaced by the latest saved version.",
    reloadError: "Could not load the latest version. Try again.",
    archivedNotice: "This template is archived. Restore it from the template list to edit it or issue letters.",
    readOnlyNotice: "You can view this template. Ask an admin for template editing access to change it.",
    loading: "Loading template…",
    loadingDetails: "Loading letter details…",
    notFound: "This template could not be found.",
    sidePanelLabel: "Template settings",
    canvasLabel: "Letter",
    questionsIntro: "HR answers these each time the letter is issued, such as a reason or an effective date.",
    questionsEmpty: "No questions yet. Add one when HR must type something in for each letter.",
    questionLabel: "Question {n}",
    answerType: "Answer type",
    answerTypes: {
      text: "Short text",
      long_text: "Paragraph",
      date: "Date",
      date_past: "Date in the past",
      currency_monthly: "Amount (₹ per month)",
      currency_annual: "Amount (₹ per year)",
      number: "Number",
      email: "Email",
      phone: "Phone",
      person_name: "Person's name",
      display_name: "Name",
      url: "Website",
      choice: "Dropdown with choices",
    },
    choices: "Choices",
    choicesHint: "Separate choices with commas. HR picks one when issuing.",
    choicesPlaceholder: "e.g. First, Second, Final",
    choicesRequired: "Add at least one choice for {label}",
    requiredAnswer: "Required",
    insertIntoLetter: "Insert into letter",
    insertQuestion: "Insert “{label}” into letter",
    removeQuestion: "Remove “{label}”",
    removeQuestionFallback: "Remove question {n}",
    removeUsedQuestionTitle: "Remove “{label}”?",
    removeUsedQuestionMessage: "This question is used in the letter. Remove it and its spots in the letter?",
    removeUsedQuestionConfirm: "Remove",
    addQuestion: "Add question",
    questionStartsWithLetter: "Question must start with a letter",
    questionClashes: "“{label}” is already a built-in detail — use a different question",
    questionTwice: "“{label}” is asked twice",
    chooseAnswerType: "Choose an answer type",
    tooManyChoices: "“{label}” can have at most {max} choices",
    tooManyQuestions: "A template can have at most {max} questions",
    unknownDetails: "Some details in this letter no longer exist ({list}) — remove the ones shown in red.",
    chooseGroup: "Choose a group",
    contentRequired: "Letter content is required",
    letterheadIntro: "Choose what is printed around the letter text.",
    letterheadOptions: {
      showLogo: { label: "Logo", hint: "Your company logo at the top of the letter." },
      showAddress: { label: "Company address", hint: "Your registered address under the logo." },
      showSignature: { label: "Signature block", hint: "Signatory name, designation and signature at the end." },
      showStamp: { label: "Stamp", hint: "Your company stamp next to the signature." },
      showFooter: { label: "Footer", hint: "A footer line at the bottom of each page." },
    },
    letterheadSettings: "Upload the logo, signature and stamp in Settings → Organization profile.",
    openSettings: "Open Organization profile",
    history: "History",
    historyNew: "History appears after you save the template.",
    historyEmpty: "No earlier versions yet. Each save keeps a copy you can restore.",
    historyError: "Could not load the history.",
    historyLoading: "Loading history…",
    version: "Version {version}",
    current: "Current",
    restore: "Restore",
    restoreVersion: "Restore version {version}",
    restoreTitle: "Restore version {version}?",
    restoreMessage: "The restored content is saved as a new version; nothing is deleted.",
    restoreMessageUnsaved: "Your unsaved changes will be lost. The restored content is saved as a new version; nothing is deleted.",
    restored: "Version {from} restored as version {to}.",
    restoreError: "Could not restore this version.",
    resetToOriginal: "Reset to original",
    resetHint: "Replace your company's wording with the original Workza wording.",
    resetTitle: "Reset to the original wording?",
    resetMessage: "Your company's wording is replaced by the original. The current wording stays in History.",
    resetMessageUnsaved:
      "Your company's wording is replaced by the original, and your unsaved changes will be lost. The saved wording stays in History.",
    reset: "Reset",
    resetDone: "Template reset to the original wording.",
    resetError: "Could not reset the template.",
    discardTitle: "Discard unsaved changes?",
    discardMessage: "Your edits to this template will be lost.",
    discard: "Discard",
    keepEditing: "Keep editing",
    insertDetail: "Insert detail",
    makeOptional: "Make optional",
    alwaysShow: "Always show",
    optionalTag: "Only shown when {label} is filled",
    otherwiseTag: "Shown instead when {label} is empty",
    sourceOnlyNotice: "This template uses advanced logic, so it can only be edited as HTML.",
    editHtml: "Edit HTML (advanced)",
    backToVisual: "Back to visual editor",
    moreOptions: "More options",
    align: {
      label: "Alignment",
      left: "Align left",
      center: "Align center",
      right: "Align right",
      justify: "Justify",
    },
    strikethrough: "Strikethrough",
    insertTable: "Insert table",
    searchDetails: "Search details",
    noDetailsMatch: "No details match “{query}”.",
    unknownDetail: "This detail no longer exists — remove it",
    saveTitle: "Save template",
    saveNote: "What did you change? (optional)",
    conflict: "Someone else saved this template — reload to see their changes.",
  },
  offers: {
    title: "Offer candidates",
    description: "Add candidates, send offer letters and turn accepted offers into employees.",
    addCandidate: "Add candidate",
    searchLabel: "Search candidates",
    searchPlaceholder: "Search by name, email or role",
    statusFilter: "Status",
    anyStatus: "Any status",
    caption: "Offer candidates",
    columns: { candidate: "Candidate", role: "Role", ctc: "Annual CTC", joining: "Joining", status: "Status", nextStep: "Next step" },
    noEmail: "No email",
    offerValidTill: "Offer valid until {date}",
    progressText: "Step {step} of {total}: {label}",
    statuses: {
      draft: "Draft",
      offered: "Offered",
      accepted: "Accepted",
      declined: "Declined",
      expired: "Expired",
      converted: "Joined",
    },
    actions: {
      sendOffer: "Send offer letter",
      sendOfferAgain: "Send offer again",
      markAccepted: "Mark accepted",
      addEmployee: "Add as employee",
      viewEmployee: "View employee",
      edit: "Edit details",
      viewLetters: "View letters",
      markDeclined: "Mark declined",
      markExpired: "Mark expired",
      delete: "Delete",
    },
    nextStepFor: "{action} for {name}",
    emptyTitle: "No candidates yet",
    emptyHint: "Add a candidate to send an offer letter.",
    emptyHintReadOnly: "Candidates added by HR appear here.",
    noMatch: "No candidates match your filters",
    noMatchHint: "Try a different search or status.",
    loadError: "Candidates could not be loaded",
    loadErrorHint: "Check your connection and try again.",
    retry: "Retry",
    confirm: {
      accepted: {
        title: "Mark {name} as accepted?",
        message: "Do this once {name} has accepted the offer. Next, you can add them as an employee.",
        confirm: "Mark accepted",
        done: "{name} marked as accepted.",
      },
      declined: {
        title: "Mark {name} as declined?",
        message: "Do this if {name} turned down the offer. You can send the offer again later.",
        confirm: "Mark declined",
        done: "{name} marked as declined.",
      },
      expired: {
        title: "Mark {name}'s offer as expired?",
        message: "Do this if the offer was not answered in time. You can send the offer again later.",
        confirm: "Mark expired",
        done: "{name}'s offer marked as expired.",
      },
    },
    noteLabel: "Note (optional)",
    noteHint: "Saved in the candidate's history.",
    employeeMissing: "Employee record no longer exists",
    history: {
      title: "History",
      empty: "No status changes recorded yet.",
      by: "by {name}",
      loading: "Loading history…",
      error: "Could not load the history.",
      retry: "Try again",
    },
    cancel: "Cancel",
    deleteTitle: "Delete {name}?",
    deleteMessage: "The candidate is removed from this list. This can't be undone.",
    deleteConfirm: "Delete",
    deleted: "{name} deleted.",
    deleteInUse:
      "{name} can't be deleted because letters have been issued to them. Void those letters in Issued letters first, or keep the record.",
    statusChanged: "{name}'s status was changed by someone else. The list has been refreshed — check it and try again.",
    candidateGone: "{name} was removed by someone else. The list has been refreshed.",
    actionError: "That didn't work. Check your connection and try again.",
    drawer: {
      addTitle: "Add candidate",
      editTitle: "Edit candidate",
      subtitle: "These details fill in the offer letter.",
      joinedSubtitle: "This candidate has joined as an employee.",
      add: "Add candidate",
      save: "Save changes",
      cancel: "Cancel",
      close: "Close",
      added: "Candidate added.",
      updated: "Candidate updated.",
      fixFields: "Please fix the highlighted fields.",
      saveError: "Could not save the candidate.",
      department: "Department",
      departmentNone: "Not decided",
      offerValidHint: "Optional. Must be on or before the joining date.",
      notesHint: "Internal only. Not shown in letters.",
    },
  },
});

export function format(str, vars = {}) {
  const values = vars || {};
  return String(str ?? "").replace(/\{(\w+)\}/g, (token, name) =>
    Object.prototype.hasOwnProperty.call(values, name) && values[name] != null ? String(values[name]) : token
  );
}
